import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Btn,Select} from '@zoer/plugin-ui/controls';
import {host} from '../bridge';
import {runProcurementAction} from './state-client';
import {PROCUREMENT_SOURCE_ADAPTERS,COLLECTION_KEY} from './source-adapters';
import {bcCheckpointHealth} from './source-health';
const BC_CHECKPOINTS=[['checkpoint:full','Current opportunities'],['checkpoint:awards','Historical awards'],['checkpoint:awards:recent','Recent awards']] as const;
function BcHealth({entries}:{entries:any[]}){
 return <div>{BC_CHECKPOINTS.map(([key,label])=>{const health=bcCheckpointHealth(key,entries.find(entry=>entry.key===key)?.value);return <section key={key} aria-label={`${label} collection health`}><h4>{label}</h4><p>{health.status}</p><dl><div><dt>Recorded scope</dt><dd>{health.scope}{health.range?` · ${health.range}`:''}</dd></div><div><dt>Checkpoint time</dt><dd>{health.checkpointTime}</dd></div><div><dt>Successful completion time for this checkpoint</dt><dd>{health.successfulAt}</dd></div></dl>{health.error&&<p role="alert">{health.error}</p>}{health.undated&&<p>Undated awards remain unverified.</p>}{health.runId&&<p>Run: {health.runId}</p>}</section>})}<p>A checkpoint time records progress, not successful collection. The host does not return a workspace-entry update timestamp. Run history retains earlier outcomes; a partial checkpoint does not establish the last successful run.</p></div>;
}
export function SourceHealth(){
 const client=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[batches,setBatches]=useState('5');
 const query=useQuery({queryKey:['catalog','procurement-health'],queryFn:()=>host('catalog.workspace',{keys:[COLLECTION_KEY,...BC_CHECKPOINTS.map(([key])=>key)]}),refetchInterval:5000});
 const state=query.data?.entries.find((e:any)=>e.key===COLLECTION_KEY)?.value;
 const run=async(mode:'resume'|'restart')=>{setBusy(true);setError('');setMessage('');try{await runProcurementAction('procurement.collect',{sourceId:'canadabuys',mode,maxBatches:Number(batches)});await client.invalidateQueries({queryKey:['catalog']});setMessage('Collection checkpoint refreshed. Review its receipt and coverage below.');}catch(e){setError((e as Error).message);await query.refetch();}finally{setBusy(false);}};
 return <section className="procurement-detail"><h2>Sources and collection health</h2><p>Availability describes the implemented connector. A successful run covers only the scope in its receipt.</p>{PROCUREMENT_SOURCE_ADAPTERS.map(source=><article className="procurement-empty" key={source.id}><h3>{source.label}</h3><p>{source.coverage}</p><dl>{Object.entries(source.capabilities).map(([name,value])=><div key={name}><dt>{name} · {value.status}</dt><dd>{value.method}</dd></div>)}</dl>{source.documentation&&<a className="procurement-link" href={source.documentation} target="_blank" rel="noreferrer">Source documentation ↗</a>}{source.id==='bc-bid'?<BcHealth entries={query.data?.entries??[]}/>:<><p role="status">{state?.status??'Not collected'} · Last attempted: {state?.lastAttemptedAt??'Never'} · Last successful collection: {state?.lastSuccessAt??'Never'}</p>{state?.error&&<p role="alert">{state.error.code}: {state.error.message}</p>}{state?.receipt&&<details open><summary>Collection receipt</summary><dl>{['sha256','retrievedAt','importedAt','byteCount','totalSourceRecords','totalRecords','excludedCount','offset'].map(key=><div key={key}><dt>{key}</dt><dd>{state.receipt[key]??'Not reported'}</dd></div>)}</dl>{state.receipt.excluded?.length > 0 && <><p>Coverage is incomplete. Locate excluded notices by CSV record number in the source snapshot with this SHA-256.</p><ul>{state.receipt.excluded.map((item:any)=><li key={item.csvRecord}>CSV record {item.csvRecord}: {item.bytes.toLocaleString()} bytes · {item.reason}</li>)}</ul></>}</details>}<label>Batches per run<Select aria-label="Collection batches" value={batches} onChange={e=>setBatches(e.target.value)}>{[1,5,10,20].map(n=><option key={n} value={n}>{n} batches</option>)}</Select></label><div className="procurement-actions"><Btn disabled={busy} onClick={()=>void run('resume')}>{busy?'Collecting…':'Collect / resume CanadaBuys'}</Btn><Btn variant="secondary" disabled={busy} onClick={()=>void run('restart')}>Start a new source snapshot</Btn></div><p>A changed dataset needs a new snapshot. Existing records are retained. HTTP access failures are reported without bypassing portal controls.</p></>}</article>)}{(error||query.error)&&<p role="alert">{error||query.error?.message}</p>}{message&&<p role="status">{message}</p>}</section>;
}
