/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContractAwardsRouteImport } from './routes/contract-awards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScraperIndexRouteImport } from './routes/scraper/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as ScraperHistoryRouteImport } from './routes/scraper/history'
import { Route as OpportunitiesProcessIdRouteImport } from './routes/opportunities/$processId'

const ContractAwardsRoute = ContractAwardsRouteImport.update({
  id: '/contract-awards',
  path: '/contract-awards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScraperIndexRoute = ScraperIndexRouteImport.update({
  id: '/scraper/',
  path: '/scraper/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScraperHistoryRoute = ScraperHistoryRouteImport.update({
  id: '/scraper/history',
  path: '/scraper/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesProcessIdRoute = OpportunitiesProcessIdRouteImport.update({
  id: '/opportunities/$processId',
  path: '/opportunities/$processId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contract-awards': typeof ContractAwardsRoute
  '/opportunities/$processId': typeof OpportunitiesProcessIdRoute
  '/scraper/history': typeof ScraperHistoryRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/scraper/': typeof ScraperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contract-awards': typeof ContractAwardsRoute
  '/opportunities/$processId': typeof OpportunitiesProcessIdRoute
  '/scraper/history': typeof ScraperHistoryRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/scraper': typeof ScraperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contract-awards': typeof ContractAwardsRoute
  '/opportunities/$processId': typeof OpportunitiesProcessIdRoute
  '/scraper/history': typeof ScraperHistoryRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/scraper/': typeof ScraperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contract-awards'
    | '/opportunities/$processId'
    | '/scraper/history'
    | '/opportunities/'
    | '/scraper/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contract-awards'
    | '/opportunities/$processId'
    | '/scraper/history'
    | '/opportunities'
    | '/scraper'
  id:
    | '__root__'
    | '/'
    | '/contract-awards'
    | '/opportunities/$processId'
    | '/scraper/history'
    | '/opportunities/'
    | '/scraper/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractAwardsRoute: typeof ContractAwardsRoute
  OpportunitiesProcessIdRoute: typeof OpportunitiesProcessIdRoute
  ScraperHistoryRoute: typeof ScraperHistoryRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ScraperIndexRoute: typeof ScraperIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contract-awards': {
      id: '/contract-awards'
      path: '/contract-awards'
      fullPath: '/contract-awards'
      preLoaderRoute: typeof ContractAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraper/': {
      id: '/scraper/'
      path: '/scraper'
      fullPath: '/scraper/'
      preLoaderRoute: typeof ScraperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraper/history': {
      id: '/scraper/history'
      path: '/scraper/history'
      fullPath: '/scraper/history'
      preLoaderRoute: typeof ScraperHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$processId': {
      id: '/opportunities/$processId'
      path: '/opportunities/$processId'
      fullPath: '/opportunities/$processId'
      preLoaderRoute: typeof OpportunitiesProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractAwardsRoute: ContractAwardsRoute,
  OpportunitiesProcessIdRoute: OpportunitiesProcessIdRoute,
  ScraperHistoryRoute: ScraperHistoryRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ScraperIndexRoute: ScraperIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
