/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContractAwardsRouteImport } from './routes/contract-awards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScraperIndexRouteImport } from './routes/scraper/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as ContractAwardsIndexRouteImport } from './routes/contract-awards/index'
import { Route as ScraperHistoryRouteImport } from './routes/scraper/history'
import { Route as OpportunitiesProcessIdRouteImport } from './routes/opportunities/$processId'
import { Route as ContractAwardsAnalysisRouteImport } from './routes/contract-awards/analysis'
import { Route as ContractAwardsAnalysisSuppliersSupplierKeyRouteImport } from './routes/contract-awards/analysis/suppliers/$supplierKey'
import { Route as ContractAwardsAnalysisOrganizationsOrganizationKeyRouteImport } from './routes/contract-awards/analysis/organizations/$organizationKey'

const ContractAwardsRoute = ContractAwardsRouteImport.update({
  id: '/contract-awards',
  path: '/contract-awards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScraperIndexRoute = ScraperIndexRouteImport.update({
  id: '/scraper/',
  path: '/scraper/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractAwardsIndexRoute = ContractAwardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractAwardsRoute,
} as any)
const ScraperHistoryRoute = ScraperHistoryRouteImport.update({
  id: '/scraper/history',
  path: '/scraper/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesProcessIdRoute = OpportunitiesProcessIdRouteImport.update({
  id: '/opportunities/$processId',
  path: '/opportunities/$processId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractAwardsAnalysisRoute = ContractAwardsAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => ContractAwardsRoute,
} as any)
const ContractAwardsAnalysisSuppliersSupplierKeyRoute =
  ContractAwardsAnalysisSuppliersSupplierKeyRouteImport.update({
    id: '/suppliers/$supplierKey',
    path: '/suppliers/$supplierKey',
    getParentRoute: () => ContractAwardsAnalysisRoute,
  } as any)
const ContractAwardsAnalysisOrganizationsOrganizationKeyRoute =
  ContractAwardsAnalysisOrganizationsOrganizationKeyRouteImport.update({
    id: '/organizations/$organizationKey',
    path: '/organizations/$organizationKey',
    getParentRoute: () => ContractAwardsAnalysisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contract-awards': typeof ContractAwardsRouteWithChildren
  '/contract-awards/analysis': typeof ContractAwardsAnalysisRouteWithChildren
  '/opportunities/$processId': typeof OpportunitiesProcessIdRoute
  '/scraper/history': typeof ScraperHistoryRoute
  '/contract-awards/': typeof ContractAwardsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/scraper/': typeof ScraperIndexRoute
  '/contract-awards/analysis/organizations/$organizationKey': typeof ContractAwardsAnalysisOrganizationsOrganizationKeyRoute
  '/contract-awards/analysis/suppliers/$supplierKey': typeof ContractAwardsAnalysisSuppliersSupplierKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contract-awards/analysis': typeof ContractAwardsAnalysisRouteWithChildren
  '/opportunities/$processId': typeof OpportunitiesProcessIdRoute
  '/scraper/history': typeof ScraperHistoryRoute
  '/contract-awards': typeof ContractAwardsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/scraper': typeof ScraperIndexRoute
  '/contract-awards/analysis/organizations/$organizationKey': typeof ContractAwardsAnalysisOrganizationsOrganizationKeyRoute
  '/contract-awards/analysis/suppliers/$supplierKey': typeof ContractAwardsAnalysisSuppliersSupplierKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contract-awards': typeof ContractAwardsRouteWithChildren
  '/contract-awards/analysis': typeof ContractAwardsAnalysisRouteWithChildren
  '/opportunities/$processId': typeof OpportunitiesProcessIdRoute
  '/scraper/history': typeof ScraperHistoryRoute
  '/contract-awards/': typeof ContractAwardsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/scraper/': typeof ScraperIndexRoute
  '/contract-awards/analysis/organizations/$organizationKey': typeof ContractAwardsAnalysisOrganizationsOrganizationKeyRoute
  '/contract-awards/analysis/suppliers/$supplierKey': typeof ContractAwardsAnalysisSuppliersSupplierKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contract-awards'
    | '/contract-awards/analysis'
    | '/opportunities/$processId'
    | '/scraper/history'
    | '/contract-awards/'
    | '/opportunities/'
    | '/scraper/'
    | '/contract-awards/analysis/organizations/$organizationKey'
    | '/contract-awards/analysis/suppliers/$supplierKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contract-awards/analysis'
    | '/opportunities/$processId'
    | '/scraper/history'
    | '/contract-awards'
    | '/opportunities'
    | '/scraper'
    | '/contract-awards/analysis/organizations/$organizationKey'
    | '/contract-awards/analysis/suppliers/$supplierKey'
  id:
    | '__root__'
    | '/'
    | '/contract-awards'
    | '/contract-awards/analysis'
    | '/opportunities/$processId'
    | '/scraper/history'
    | '/contract-awards/'
    | '/opportunities/'
    | '/scraper/'
    | '/contract-awards/analysis/organizations/$organizationKey'
    | '/contract-awards/analysis/suppliers/$supplierKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractAwardsRoute: typeof ContractAwardsRouteWithChildren
  OpportunitiesProcessIdRoute: typeof OpportunitiesProcessIdRoute
  ScraperHistoryRoute: typeof ScraperHistoryRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ScraperIndexRoute: typeof ScraperIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contract-awards': {
      id: '/contract-awards'
      path: '/contract-awards'
      fullPath: '/contract-awards'
      preLoaderRoute: typeof ContractAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraper/': {
      id: '/scraper/'
      path: '/scraper'
      fullPath: '/scraper/'
      preLoaderRoute: typeof ScraperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract-awards/': {
      id: '/contract-awards/'
      path: '/'
      fullPath: '/contract-awards/'
      preLoaderRoute: typeof ContractAwardsIndexRouteImport
      parentRoute: typeof ContractAwardsRoute
    }
    '/scraper/history': {
      id: '/scraper/history'
      path: '/scraper/history'
      fullPath: '/scraper/history'
      preLoaderRoute: typeof ScraperHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$processId': {
      id: '/opportunities/$processId'
      path: '/opportunities/$processId'
      fullPath: '/opportunities/$processId'
      preLoaderRoute: typeof OpportunitiesProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract-awards/analysis': {
      id: '/contract-awards/analysis'
      path: '/analysis'
      fullPath: '/contract-awards/analysis'
      preLoaderRoute: typeof ContractAwardsAnalysisRouteImport
      parentRoute: typeof ContractAwardsRoute
    }
    '/contract-awards/analysis/suppliers/$supplierKey': {
      id: '/contract-awards/analysis/suppliers/$supplierKey'
      path: '/suppliers/$supplierKey'
      fullPath: '/contract-awards/analysis/suppliers/$supplierKey'
      preLoaderRoute: typeof ContractAwardsAnalysisSuppliersSupplierKeyRouteImport
      parentRoute: typeof ContractAwardsAnalysisRoute
    }
    '/contract-awards/analysis/organizations/$organizationKey': {
      id: '/contract-awards/analysis/organizations/$organizationKey'
      path: '/organizations/$organizationKey'
      fullPath: '/contract-awards/analysis/organizations/$organizationKey'
      preLoaderRoute: typeof ContractAwardsAnalysisOrganizationsOrganizationKeyRouteImport
      parentRoute: typeof ContractAwardsAnalysisRoute
    }
  }
}

interface ContractAwardsAnalysisRouteChildren {
  ContractAwardsAnalysisOrganizationsOrganizationKeyRoute: typeof ContractAwardsAnalysisOrganizationsOrganizationKeyRoute
  ContractAwardsAnalysisSuppliersSupplierKeyRoute: typeof ContractAwardsAnalysisSuppliersSupplierKeyRoute
}

const ContractAwardsAnalysisRouteChildren: ContractAwardsAnalysisRouteChildren =
  {
    ContractAwardsAnalysisOrganizationsOrganizationKeyRoute:
      ContractAwardsAnalysisOrganizationsOrganizationKeyRoute,
    ContractAwardsAnalysisSuppliersSupplierKeyRoute:
      ContractAwardsAnalysisSuppliersSupplierKeyRoute,
  }

const ContractAwardsAnalysisRouteWithChildren =
  ContractAwardsAnalysisRoute._addFileChildren(
    ContractAwardsAnalysisRouteChildren,
  )

interface ContractAwardsRouteChildren {
  ContractAwardsAnalysisRoute: typeof ContractAwardsAnalysisRouteWithChildren
  ContractAwardsIndexRoute: typeof ContractAwardsIndexRoute
}

const ContractAwardsRouteChildren: ContractAwardsRouteChildren = {
  ContractAwardsAnalysisRoute: ContractAwardsAnalysisRouteWithChildren,
  ContractAwardsIndexRoute: ContractAwardsIndexRoute,
}

const ContractAwardsRouteWithChildren = ContractAwardsRoute._addFileChildren(
  ContractAwardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractAwardsRoute: ContractAwardsRouteWithChildren,
  OpportunitiesProcessIdRoute: OpportunitiesProcessIdRoute,
  ScraperHistoryRoute: ScraperHistoryRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ScraperIndexRoute: ScraperIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
